### ISSUE TITLE
线程失控

### ISSUE THREAD

**Issue by AceBear** [InCar/rooster-gather#4]
```java
GatherChannelHandler(GatherSlot slot) {
		_slot = slot;
		_parser = slot.getDataParser();
		_threadPool = Executors.newFixedThreadPool(20);
}
```
[GatherChannelHandler.java#L48](https://github.com/InCar/rooster-gather/blob/37738f516aa06a291f8dc1d71d69bc73cc014a45/src/main/java/com/incarcloud/rooster/gather/GatherChannelHandler.java#L48)

这究竟会开多少个线程？消耗多少内存？有过计算没有？

**Comment by youbeiwuhuan** [comment]
这里设计的是总共20个线程，一个channelRead创建一个任务对象缓存在线程池的队列里，由线程池中空闲线程去队列中取任务来执行

**Comment by AceBear** [comment]
自己去做个实验，看看netty里的channelHandle是怎么工作的
